### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jbgi** [osxhacker/ReactiveMongo-Criteria#1]
This is an awesome project that deserves a release.
Any plan?

**Comment by osxhacker** [comment]
Thanks for the kind words!

Yes, a release to Maven Central is planned.  I need to get with Stephane in the ReactiveMongo team to determine what organizationId to use.  If I can't get permission for one which is related to ReactiveMongo, then I will publish this under an organizationId which I can reliably publish under.

**Comment by osxhacker** [comment]
Discussion with an official ReactiveMongo representative did not go "smoothly."

Therefore, this project will be released under an organizationId of which I am able to publish as well as a refactoring of the package name to disassociate from the defunct ReactiveMongo-Extensions project and the ReactiveMongo organization in general.  The organizationId most likely will be:

com.tubrossystems

And the base package name will most likely be:

com.tubrosssytems.rmongo.dsl.criteria

This will be a breaking change to what exists now and, as such, the README.md will be updated accordingly.

**Comment by Katrix** [comment]
Is this still maintained? If so, when are you planning to do the release?

**Comment by osxhacker** [comment]
@Katrix- Yes, this project is maintained.  A fix addressing an issue introduced by changes in ReactiveMongo recently was just pushed a few minutes ago.

As far as getting a bundle out to Maven Central, the main issue really has been my finding the time to get versed in the prerequisites for publishing, then satisfying same.

**Comment by danslapman** [comment]
@osxhacker how about publishing to Bintray? It's much less bureaucratic.

**Comment by osxhacker** [comment]
A new issue, #4 , has been logged which has elevated the need for an indepdendent release to be produced.  The plan is to refactor this project such that both ReactiveMongo and the official MongoDB Scala driver is supported.

Since changing the organizationId is a breaking change, this is a good time to introduce cross-Scala version support for Scala versions "2.11", "2.12", and "2.13".

The ReactiveMongo-Criteria version will change as well in order to no longer be dependent upon the ReactiveMongo version.

**Comment by osxhacker** [comment]
This project is the process of being archived.  New work is now being done in [scala-bson-query](https://github.com/osxhacker/scala-bson-query)
